DMMVCGestorDeTareasMagic/Controllers/DMCategoriasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DMMVCGestorDeTareasMagic.Models;

namespace DMMVCGestorDeTareasMagic.Controllers
{
    public class DMCategoriasController : Controller
    {
        private readonly DMMVCGestorDeTareasMagicContext _context;

        public DMCategoriasController(DMMVCGestorDeTareasMagicContext context)
        {
            _context = context;
        }

        // GET: DMCategorias
        public async Task<IActionResult> Index()
        {
            return View(await _context.DMCategoria.ToListAsync());
        }

        // GET: DMCategorias/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dMCategoria = await _context.DMCategoria
                .FirstOrDefaultAsync(m => m.DMCategoriaID == id);
            if (dMCategoria == null)
            {
                return NotFound();
            }

            return View(dMCategoria);
        }

        // GET: DMCategorias/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: DMCategorias/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DMCategoriaID,DMNombre,DMDescripcion")] DMCategoria dMCategoria)
        {
            if (ModelState.IsValid)
            {
                _context.Add(dMCategoria);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(dMCategoria);
        }

        // GET: DMCategorias/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dMCategoria = await _context.DMCategoria.FindAsync(id);
            if (dMCategoria == null)
            {
                return NotFound();
            }
            return View(dMCategoria);
        }

        // POST: DMCategorias/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DMCategoriaID,DMNombre,DMDescripcion")] DMCategoria dMCategoria)
        {
            if (id != dMCategoria.DMCategoriaID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(dMCategoria);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DMCategoriaExists(dMCategoria.DMCategoriaID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(dMCategoria);
        }

        // GET: DMCategorias/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dMCategoria = await _context.DMCategoria
                .FirstOrDefaultAsync(m => m.DMCategoriaID == id);
            if (dMCategoria == null)
            {
                return NotFound();
            }

            return View(dMCategoria);
        }

        // POST: DMCategorias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var dMCategoria = await _context.DMCategoria.FindAsync(id);
            if (dMCategoria != null)
            {
                _context.DMCategoria.Remove(dMCategoria);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DMCategoriaExists(int id)
        {
            return _context.DMCategoria.Any(e => e.DMCategoriaID == id);
        }
    }
}

DMMVCGestorDeTareasMagic/Controllers/DMPrioridadsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DMMVCGestorDeTareasMagic.Models;

namespace DMMVCGestorDeTareasMagic.Controllers
{
    public class DMPrioridadsController : Controller
    {
        private readonly DMMVCGestorDeTareasMagicContext _context;

        public DMPrioridadsController(DMMVCGestorDeTareasMagicContext context)
        {
            _context = context;
        }

        // GET: DMPrioridads
        public async Task<IActionResult> Index()
        {
            return View(await _context.DMPrioridad.ToListAsync());
        }

        // GET: DMPrioridads/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dMPrioridad = await _context.DMPrioridad
                .FirstOrDefaultAsync(m => m.DMPrioridadID == id);
            if (dMPrioridad == null)
            {
                return NotFound();
            }

            return View(dMPrioridad);
        }

        // GET: DMPrioridads/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: DMPrioridads/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DMPrioridadID,DMNombre,DMDescripcion")] DMPrioridad dMPrioridad)
        {
            if (ModelState.IsValid)
            {
                _context.Add(dMPrioridad);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(dMPrioridad);
        }

        // GET: DMPrioridads/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dMPrioridad = await _context.DMPrioridad.FindAsync(id);
            if (dMPrioridad == null)
            {
                return NotFound();
            }
            return View(dMPrioridad);
        }

        // POST: DMPrioridads/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DMPrioridadID,DMNombre,DMDescripcion")] DMPrioridad dMPrioridad)
        {
            if (id != dMPrioridad.DMPrioridadID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(dMPrioridad);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DMPrioridadExists(dMPrioridad.DMPrioridadID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(dMPrioridad);
        }

        // GET: DMPrioridads/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dMPrioridad = await _context.DMPrioridad
                .FirstOrDefaultAsync(m => m.DMPrioridadID == id);
            if (dMPrioridad == null)
            {
                return NotFound();
            }

            return View(dMPrioridad);
        }

        // POST: DMPrioridads/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var dMPrioridad = await _context.DMPrioridad.FindAsync(id);
            if (dMPrioridad != null)
            {
                _context.DMPrioridad.Remove(dMPrioridad);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DMPrioridadExists(int id)
        {
            return _context.DMPrioridad.Any(e => e.DMPrioridadID == id);
        }
    }
}

DMMVCGestorDeTareasMagic/Controllers/DMTareasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DMMVCGestorDeTareasMagic.Models;

namespace DMMVCGestorDeTareasMagic.Controllers
{
    public class DMTareasController : Controller
    {
        private readonly DMMVCGestorDeTareasMagicContext _context;

        public DMTareasController(DMMVCGestorDeTareasMagicContext context)
        {
            _context = context;
        }

        // GET: DMTareas
        public async Task<IActionResult> Index()
        {
            var dMMVCGestorDeTareasMagicContext = _context.DMTarea.Include(d => d.DMPrioridad);
            return View(await dMMVCGestorDeTareasMagicContext.ToListAsync());
        }

        // GET: DMTareas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dMTarea = await _context.DMTarea
                .Include(d => d.DMPrioridad)
                .FirstOrDefaultAsync(m => m.DMTareaID == id);
            if (dMTarea == null)
            {
                return NotFound();
            }

            return View(dMTarea);
        }

        // GET: DMTareas/Create
        public IActionResult Create()
        {
            ViewData["DMPrioridadID"] = new SelectList(_context.DMPrioridad, "DMPrioridadID", "DMDescripcion");
            return View();
        }

        // POST: DMTareas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DMTareaID,DMTitulo,DMDescripcion,DMFechaVencimiento,DMPrioridadID,DMCategoriaID")] DMTarea dMTarea)
        {
            if (ModelState.IsValid)
            {
                _context.Add(dMTarea);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["DMPrioridadID"] = new SelectList(_context.DMPrioridad, "DMPrioridadID", "DMDescripcion", dMTarea.DMPrioridadID);
            return View(dMTarea);
        }

        // GET: DMTareas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dMTarea = await _context.DMTarea.FindAsync(id);
            if (dMTarea == null)
            {
                return NotFound();
            }
            ViewData["DMPrioridadID"] = new SelectList(_context.DMPrioridad, "DMPrioridadID", "DMDescripcion", dMTarea.DMPrioridadID);
            return View(dMTarea);
        }

        // POST: DMTareas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DMTareaID,DMTitulo,DMDescripcion,DMFechaVencimiento,DMPrioridadID,DMCategoriaID")] DMTarea dMTarea)
        {
            if (id != dMTarea.DMTareaID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(dMTarea);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DMTareaExists(dMTarea.DMTareaID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DMPrioridadID"] = new SelectList(_context.DMPrioridad, "DMPrioridadID", "DMDescripcion", dMTarea.DMPrioridadID);
            return View(dMTarea);
        }

        // GET: DMTareas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dMTarea = await _context.DMTarea
                .Include(d => d.DMPrioridad)
                .FirstOrDefaultAsync(m => m.DMTareaID == id);
            if (dMTarea == null)
            {
                return NotFound();
            }

            return View(dMTarea);
        }

        // POST: DMTareas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var dMTarea = await _context.DMTarea.FindAsync(id);
            if (dMTarea != null)
            {
                _context.DMTarea.Remove(dMTarea);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DMTareaExists(int id)
        {
            return _context.DMTarea.Any(e => e.DMTareaID == id);
        }
    }
}

DMMVCGestorDeTareasMagic/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DMMVCGestorDeTareasMagic</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DMMVCGestorDeTareasMagic.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">| Gestor de Tareas | Daniela Mora</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                GestorDeTareas
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="dropdown-item"
                                       asp-area=""
                                       asp-controller="DMCategorias"
                                       asp-action="Index">
                                        Agregar Categorias
                                    </a>
                                </li>

                                <li>
                                    <a class="dropdown-item"
                                       asp-area=""
                                       asp-controller="DMPrioridads"
                                       asp-action="Index">
                                        Agregar Prioridades
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item"
                                       asp-area=""
                                       asp-controller="DMTareas"
                                       asp-action="Index">
                                        Agregar Tareas
                                    </a>
                                </li>

                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - DanielaMora - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>